spring:
  application:
    name: LetsChat

# Database Connectivity
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: syoo.shop@gmail.com
    password: ${EMAIL_CREDENTIAL}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# Server Port
server:
  port: 8080

# File
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB


jwt:
  secret: ${JWT_SECRET}

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
  redirect:
    uri: https://syoo.shop/api/oauth/callback
  logout:
    redirect:
      uri: https://syoo.shop/login
  callback:
    redirect:
      uri: https://syoo.shop/chat-list

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: https://syoo.shop/api/oauth/google/callback
  logout:
    redirect:
      uri: https://syoo.shop/login
  callback:
    redirect:
       uri: https://syoo.shop/chat-list
